@organizer @draw @integrity
Feature: The draw
  As a captain or spectator
  I want the bracket to be generated by a published, reproducible seed
  So that I can verify the organizer did not arrange the field to suit anyone

  The draw is a seeded shuffle of the published roster. Both inputs are public:
  `roster.md` in the roster repo, and "Draw seed" in `config/tournament.md`.
  Anyone can run the same shuffle and get the same bracket. This is the
  platform's answer to having a single privileged role — make the privileged
  act independently checkable.

  Nothing about the bracket is stored. It is rebuilt from those two inputs
  every time anybody looks at it, in the browser and in the CLI alike.

  Background:
    Given a confirmed roster has been published to roster.md
    And config/tournament.md carries the draw seed

  Rule: The draw is reproducible by anyone

    @smoke @critical
    Scenario: Running the draw
      Given at least two teams are on the roster
      When the organizer runs the draw
      Then a seed is published to config/tournament.md via gh
      And the bracket every visitor sees is built from the roster and that seed

    @critical @verifiable
    Scenario: A sceptic checks the organizer's work
      Given a spectator has roster.md and the published seed
      When they run the same shuffle themselves
      Then they get the identical bracket, match for match
      # The organizer cannot rig the draw without publishing a seed that does
      # not produce the bracket they published.

    Scenario: The same seed and field always give the same bracket
      When the bracket is rebuilt any number of times
      Then it is identical every time
      And no wall-clock value affects it

    Scenario: A different seed gives a different bracket
      Given the same roster
      When a different seed is used
      Then the pairings differ

  Rule: Row order is part of the input, so it is canonical

    @critical @determinism
    Scenario: The bracket does not depend on how the roster file was written
      Given the same teams rendered into roster.md in two different orders
      Then the two files are byte-identical, because rows are sorted by code
      And rebuilding from either produces the same bracket
      # Without this, a stray hand edit that reordered rows would silently
      # reshuffle a tournament that was already under way.

  Rule: Fields that are not a power of two still work

    Scenario: Byes are distributed, never doubled up
      Given a field whose size is not a power of two
      When the draw runs
      Then the bracket is padded to the next power of two
      And no match has two empty sides
      And a team drawn against an empty side advances without playing

    Scenario: A draw needs a field
      Given fewer than two teams are on the roster
      When the organizer runs the draw
      Then it is refused and nothing is published

  Rule: The draw freezes the tournament

    @critical @lock
    Scenario: Re-drawing over published results is refused
      Given results have been confirmed under the current seed
      When the organizer runs the draw again
      Then it is refused
      And the refusal names every result the new seed would orphan
      And nothing is published

    @lock
    Scenario: Re-drawing before anything is published is allowed on purpose
      Given the seed is set but results.md is empty
      When the organizer re-runs the draw with an explicit force
      Then a new seed is published
      # Nobody has relied on the old bracket yet, so this is a correction,
      # not a rewrite of history.

    @lock
    Scenario: The roster is closed from this moment
      Given the draw has run
      When a new entry arrives
      Then it cannot be added to the field
      # See 03_captain_registration. The two locks are the same lock.
