@organizer @draw @integrity
Feature: The draw
  As a captain or spectator
  I want the bracket to be generated by a published, reproducible seed
  So that I can verify the organizer did not arrange the field to suit anyone

  The draw is a seeded shuffle. Publish the seed and the field, and anyone can
  regenerate the identical bracket. This is the platform's answer to having a
  single privileged role: make the privileged act independently checkable.

  Background:
    Given the organizer console is unlocked
    And the roster holds teams that have not yet been drawn

  Rule: The draw is deterministic given a seed and a field

    @smoke @critical
    Scenario: Running the draw
      Given 8 teams are on the roster
      When the organizer runs the draw with seed "autumn-2026"
      Then a 3-round single-elimination bracket is built
      And the rounds are labelled
        | slots | label          |
        | 8     | Quarter-finals |
        | 4     | Semi-finals    |
        | 2     | The Final      |
      And every team appears exactly once in the first round

    @determinism @critical
    Scenario: The same seed and field always produce the same bracket
      Given 8 teams are on the roster
      When the draw is run twice with seed "autumn-2026"
      Then both brackets are identical match for match

    @determinism
    Scenario: A different seed produces a different bracket
      Given 8 teams are on the roster
      When the draw is run with seed "seed-a"
      And separately with seed "seed-b"
      Then the two brackets differ

    @determinism
    Scenario: An unseeded draw generates and records its own seed
      When the organizer runs the draw leaving the seed blank
      Then a seed is generated from the tournament name and the current time
      And that seed is recorded on the bracket
      And it is published so the draw stays verifiable

  Rule: Fields that are not a power of two get byes, never dead matches

    @byes
    Scenario Outline: Distributing byes across any field size
      Given <teams> teams are on the roster
      When the draw is run
      Then the bracket has <rounds> rounds
      And <byes> teams receive a first-round bye
      And no match has two empty slots

      Examples:
        | teams | rounds | byes |
        | 2     | 1      | 0    |
        | 3     | 2      | 1    |
        | 6     | 3      | 2    |
        | 8     | 3      | 0    |
        | 12    | 4      | 4    |
        | 32    | 5      | 0    |

    @byes
    Scenario: A bye advances automatically
      Given team "QMMD" receives a first-round bye
      When the draw completes
      Then "QMMD" is already recorded as the winner of that match
      And "QMMD" appears in the second round without playing
      And no score report is expected for the bye

  Rule: The draw aligns to the published schedule

    @schedule
    Scenario: Rounds inherit their start times from the phases
      Given the tournament declares knockout phases ending in "The Final"
      When a 3-round bracket is drawn
      Then the rounds are aligned to the last 3 knockout phases
      And each round carries the start time of its phase
      And captains see that time on their fixture

    @schedule
    Scenario: More rounds than phases reuses the earliest phase start
      Given the tournament declares 3 knockout phases
      When a 5-round bracket is drawn
      Then the earliest declared start is reused for the surplus early rounds
      And no round is left without a start time

  Rule: Running the draw is a deliberate, locking act

    @critical @confirmation
    Scenario: The draw is confirmed before it locks the field
      Given 8 teams are on the roster
      When the organizer initiates the draw
      Then they are warned this locks the field
      And the bracket is only built once they confirm

    @critical
    Scenario: The draw cannot be repeated
      Given a bracket has been drawn
      Then the draw control is no longer offered
      And the console presents the result queue in its place

  @audit
  Scenario: A spectator verifies the draw independently
    Given the published bracket carries seed "autumn-2026"
    And the field of team codes is published
    When a spectator runs the same seeded shuffle over the same field
    Then they reproduce the published bracket exactly
    And any discrepancy is evidence the bracket was not drawn as claimed
